### PR TITLE
Chunksize plots size c 1

### PR DESCRIPTION
**Pull request by will-moore**
On top of #18.

 - Use pixel sizes (X and Y) on x-axis. Since those are the units we use elsewhere in the text. Figure legend is "Moderate chunk sizes were chosen to cover most real-world scenarios: 2D-chunks were 256x256"
 
Screenshot 2021-04-08 at 15 21 01

Screenshot 2021-04-08 at 16 47 45

### CODE REVIEW

**Comment by will-moore** [comment]
Just running:
```
$ python notebooks/chunks.py chunksplot.png
```

chunksplot

I can have a go at the layout issues...

**Comment by will-moore** [comment]
chunksplot

Some improvements to layout:

**Comment by will-moore** [comment]
Looking at this figure, the initial impression is that the axis range has been poorly chosen as there's nothing to indicate that I should be comparing the lines directly between each plot (they look like independent plots, unlike the 'access times' plots for part A). 

Is it important that we use the same scales for both plots? Do we need to directly compare the number of chunks for each of our sample images? I thought that the value of each plot was the relationship between file-count and chunk size for each independent image.

chunksplot

Without using the same scale:

chunksplot

**Comment by joshmoore** [comment]
y-scale I find pretty important to keep the same. It probably will make it clearer to share the axis between the two (and save some space). x-scale I could see either way.

**Pull request merged**
